// @autogenerated

// WARNING THIS FILE IS AUTOGENERATED! DO NOT EDIT!

import React from 'react';

import H1 from '@govtnz/ds/build/react-ts/H1';
import '../../commons/styles/ds/themed-H1.scss';

import PatternsPage from '../../components/PatternsPage';
import onChangeGenerator from '../../commons/onChangeGenerator';

const PageContent = (props) => <React.Fragment>
<H1 styleSize="xlarge" id="main-heading">Pattern library</H1>
<p>patternlibrary/index.json
    Pages in this demo site are constructed using individual modules — little lego blocks that we glue together into pages. This lets you compose really expressive pages, where content can appear in flexible order and all the pieces fit nicely. If you need, you can get a component over our JSON API to check that your HTML looks right!
    <a class='btn btn--primary' href='/api/css'>Get the CSS</a>  <a class='btn btn--primary' href='/api/js'>Get the Javascript</a> 
    The source code for the project is available on GitHub here: <a href='https://github.com/NZTA/nzta-prototype'>https://github.com/NZTA/nzta-prototype</a>
</p>
</React.Fragment>

const template = (props) => {
    return (
        <PatternsPage
            title="Pattern library"
            pageProps={props}
            PageContent={PageContent}
        />
    );
};

export default template;
